# Numpy practice

In [1]:
#This imports numpy as alias np
import numpy as np

In [2]:
#To create an array
a = np.array([1,2,3,4])

print(a)

print(a.ndim) #Number of dimensions

print(a.shape) #Shape of the array

print(a.size) #Number of elements in array

print(a.dtype) #Datatype of elements

[1 2 3 4]
1
(4,)
4
int64


In [3]:
b = np.array([ [1,2,3,4], [5,6,7,8] ])

print(b)

print(b.ndim) #Number of dimensions

print(b.shape) #Shape of the array

print(b.size) #Number of elements in array

print(b.dtype) #Datatype of elements

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
8
int64


In [4]:
c = np.arange(1,11,2) #Initial,final,jump - final is exclusive and initial inclusive
print(c)
print(type(c))

c = np.arange(-1,2,0.4) #Also accepts float arguments
print(c)

[1 3 5 7 9]
<class 'numpy.ndarray'>
[-1.  -0.6 -0.2  0.2  0.6  1.   1.4  1.8]


In [5]:
b = b.reshape(-1,2) #Reshapes into 4*2. -1 means dimension is calculated automatically
print(b)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [6]:
e = np.array([ [1,2j], [3,4j] ],dtype=complex)
print(e)

[[1.+0.j 0.+2.j]
 [3.+0.j 0.+4.j]]


In [7]:
#Creates a 5*5 matrix with all zeros 
f = np.zeros((5,5))
print(f)

#Creates a 5*5 matrix with all zeros
f = np.ones((5,5))
print(f)

#Creates a 5*5 identity matrix
f = np.eye(5)
print(f)

#Creates a 5*5 matrix with random elements
f = np.empty((5,5))
print(f)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [8]:
#When values dont fit in the dtype then they overflow
g = np.array([1,2,56,12,255,344],dtype='int8')
print(g)

#Unsigned int of 8 bits
g = np.array([1,2,56,12,255,344],dtype='uint8')
print(g)

[ 1  2 56 12 -1 88]
[  1   2  56  12 255  88]


In [9]:
#This generates 100 points between 0 to 50
h = np.linspace(0,50,100)
print(h)

[ 0.          0.50505051  1.01010101  1.51515152  2.02020202  2.52525253
  3.03030303  3.53535354  4.04040404  4.54545455  5.05050505  5.55555556
  6.06060606  6.56565657  7.07070707  7.57575758  8.08080808  8.58585859
  9.09090909  9.5959596  10.1010101  10.60606061 11.11111111 11.61616162
 12.12121212 12.62626263 13.13131313 13.63636364 14.14141414 14.64646465
 15.15151515 15.65656566 16.16161616 16.66666667 17.17171717 17.67676768
 18.18181818 18.68686869 19.19191919 19.6969697  20.2020202  20.70707071
 21.21212121 21.71717172 22.22222222 22.72727273 23.23232323 23.73737374
 24.24242424 24.74747475 25.25252525 25.75757576 26.26262626 26.76767677
 27.27272727 27.77777778 28.28282828 28.78787879 29.29292929 29.7979798
 30.3030303  30.80808081 31.31313131 31.81818182 32.32323232 32.82828283
 33.33333333 33.83838384 34.34343434 34.84848485 35.35353535 35.85858586
 36.36363636 36.86868687 37.37373737 37.87878788 38.38383838 38.88888889
 39.39393939 39.8989899  40.4040404  40.90909091 41.

In [10]:
#Generates sine values for all corresponding values in h
i = np.sin(h)

In [11]:
from matplotlib import pyplot as plt
#plot function takes first arg as x points and second arg as y points
plt.plot(h,i)
plt.show()

<Figure size 640x480 with 1 Axes>

In [12]:
j = np.array([10,20,30,40])
h = np.arange(4) + 1 #Broadcasting all elements are added with 1

print(j-h) #Element wise subtraction

print(j+h) #Element wise addition

print(j*h) #Element wise multiplication

print(j/h) #Element wise division

print(j**h) #All elements in j are raised to powers of corresponding elements in h

print(j**2) #Square of all elements in j

print(j%h) #Modulus of elements in j by elements in h

print(j<20) #Return true if j < 20

print(np.exp(h)) #Prints exponent of h

print(h[1:3]) #Slicing operation

h[0:3:2] = -10 #Starting from 0th index(inclusive) to 3rd index(exclusive) set every 2nd element to -10

print(h)

print(h[ : :-1]) #Reverses the list

[ 9 18 27 36]
[11 22 33 44]
[ 10  40  90 160]
[10. 10. 10. 10.]
[     10     400   27000 2560000]
[ 100  400  900 1600]
[0 0 0 0]
[ True False False False]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[2 3]
[-10   2 -10   4]
[  4 -10   2 -10]


In [13]:
k = np.array([ [1,2],[3,4] ])
l = np.array([ [5,6],[7,8] ])

print(k*l) #Element wise product

print(k@l) #Dot product works for python >= 3.5

print(k.dot(l)) #Dot product

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [14]:
m = np.array( [ [1,3,5,7,9],
                [0,2,4,6,8] ] )

print(np.sum(m)) #Sums all elements

print(m.min()) #Takes min of all elements

print(m.max()) #Max of all elements

print(np.sum(m,axis=0)) #Axis = 0 means operations will take place along columns

print(np.sum(m,axis=1)) #Axis = 1 means operations will take place along rows

print(m.min(axis=0)) #Minimum along columns

45
0
9
[ 1  5  9 13 17]
[25 20]
[0 2 4 6 8]


In [45]:
n = np.random.random((3,3)) #Creates a 3*3 matrix with random floats between 0 to 1
print(n)
n = np.random.randint(0,10,size=(2,4)) #Returns a 2*4 matrix with integers between 0 to 10
print(n)
n = np.arange(10)
print(n)
np.random.shuffle(n) #Randomly shuffles an array
print(n)
n = np.random.randn(1,10) #Generates a normal distribution
print(n)

[[0.70822152 0.72644829 0.22423853]
 [0.32598715 0.22957445 0.63768434]
 [0.90665678 0.36877296 0.57662733]]
[[0 2 3 2]
 [6 6 2 1]]
[0 1 2 3 4 5 6 7 8 9]
[5 3 2 1 4 6 8 0 7 9]
[[ 0.12729406  0.28441646  1.17442393  1.21491821  0.58552576  0.33027799
   0.62775446  0.3769884   1.63301204 -0.2675088 ]]


#### The dots (...) represent as many colons as needed to produce a complete indexing. If x is an array with 5 axes

#### x[1,2,...] is equivalent to x[1,2,:,:,:]
#### x[...,3] to x[:,:,:,:,3]
#### x[4,...,5,:] to x[4,:,:,5,:]


In [56]:
o = np.arange(16).reshape((4,4))
print(o)

#Print transpose of the array
print(o.T)

#Iterating is done row-wise
for row in o:
    print(row)
    
#Iterating is done element-wise
for element in o.flat:
    print(element)
    
#Takes floor of all elements
o = np.array([1.2,3.4,5.6,7.8])
o = np.floor(o)
print(o)

#We can also use resize. It changes dimension inplace
o = o.reshape((2,2))
print(o)

#Flattens the array
o = o.ravel() 
print(o)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
[1. 3. 5. 7.]
[[1. 3.]
 [5. 7.]]
[1. 3. 5. 7.]


## Stacking arrays together

In [58]:
p = np.array([[1,2],[3,4]])
q = np.array([[5,6],[7,8]])

#Stacks top to bottom along vertical axis
print(np.vstack((p,q)))

#Stacks from side to side along horizontal axis
print(np.hstack((p,q)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [62]:
r = np.floor(10*np.random.random((2,12)))
print(r)

#Splits the matrix into 3 equal parts horizontally
print(np.hsplit(r,3))

#Splits the matrix into 2 equal parts vertically
print(np.vsplit(r,2))

[[0. 1. 7. 7. 5. 1. 8. 1. 5. 9. 4. 7.]
 [3. 6. 9. 4. 5. 1. 0. 4. 8. 4. 5. 3.]]
[array([[0., 1., 7., 7.],
       [3., 6., 9., 4.]]), array([[5., 1., 8., 1.],
       [5., 1., 0., 4.]]), array([[5., 9., 4., 7.],
       [8., 4., 5., 3.]])]
[array([[0., 1., 7., 7., 5., 1., 8., 1., 5., 9., 4., 7.]]), array([[3., 6., 9., 4., 5., 1., 0., 4., 8., 4., 5., 3.]])]
